### ISSUE TITLE
add powerup items and lives system + UI

### ISSUE THREAD

**Issue by ChenKangg** [clarencepohh/Orbital23#18]
add heart, smash and obstacle items

**Comment by clarencepohh** [comment]
partially complete. moving to MS2 tag for future reference.
to do: 
- sprite creation for smash power up
- attach sprites for obstacles 
- refine spawning system to prevent out of bounds spawn

**Comment by clarencepohh** [comment]
for MS2 current progress 13/6:
- smash power up added with sprite
- obstacle sprite attached
- spawning system somewhat refined 
   -- they don't spawn on each other any more; provided they are same type of object. 
   -- can still go out of bounds
